// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHv97qwnfGtnOO-yrxpKeGkWAE0ji48oo',
    appId: '1:434415085853:web:55f973ce3dfe8eda1d99f4',
    messagingSenderId: '434415085853',
    projectId: 'cw06-2dcb6',
    authDomain: 'cw06-2dcb6.firebaseapp.com',
    storageBucket: 'cw06-2dcb6.firebasestorage.app',
    measurementId: 'G-BGJ5JFZ1LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmZVj1eA1uisID5XQndZh5bmQAdeR-OU',
    appId: '1:434415085853:android:886687fdf48320c61d99f4',
    messagingSenderId: '434415085853',
    projectId: 'cw06-2dcb6',
    storageBucket: 'cw06-2dcb6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHv97qwnfGtnOO-yrxpKeGkWAE0ji48oo',
    appId: '1:434415085853:web:1a764bf09b9908aa1d99f4',
    messagingSenderId: '434415085853',
    projectId: 'cw06-2dcb6',
    authDomain: 'cw06-2dcb6.firebaseapp.com',
    storageBucket: 'cw06-2dcb6.firebasestorage.app',
    measurementId: 'G-MDQJXTEMTL',
  );
}
